#!/usr/bin/env bash
#MISE description="Run all unit tests in the tests directory using uv and pytest."

set -euo pipefail

echo "[*] Running unit tests..."
go test ./... -count=1
if [ $? -ne 0 ]; then
  echo "[!] Unit tests failed."
  exit 1
fi
echo "[*] Unit tests passed."
