#!/usr/bin/env bash
#MISE description="Run Go linter, run tests, and validate the SAM template"

echo "[*] Running code linter..."
golangci-lint run ./...
echo
echo "[*] Running unit tests..."
mise run test
echo
SAM_DIR="${MISE_PROJECT_ROOT:-$(pwd)}/sam"
echo "[*] Validating SAM template at $SAM_DIR/template.yaml..."
sam validate --template "$SAM_DIR/template.yaml" --lint --region us-east-1
