[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aws-lambda-container-images"
version = "0.1.0"
[tool.uv]
[tool.pytest.ini_options]
testpaths = ["tests"]
